### ISSUE TITLE
Issue with rain totals on WS-2000

### ISSUE THREAD

**Issue by socalrds** [simplextech/udi-ambientweather-poly#1]
ambientweather-poly.py errors at line 192 as the WS-2000 does not return a totalrainin data element, but there is no condition for its MAC type to exclude it and use yearlyrainin.    When this errors all remaining data elements are not loaded.   My mac starts with 3C71BF, not sure if this is the same for all WS-2000 units

**Comment by simplextech** [comment]
This was resolved in the re-write release.  If you still have issues let me know.
